// SAVe_New/frontend/src/components/sections/SinteseAnalitica.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import api from "../../lib/api";

    export let caseId: string;

    let data: any = {};
    let loading = true;
    let saving = false;
    let saveTimeout: any;
    let lastSavedData: string = "";
    let saveStatus = "";

    // Reactive loading when caseId changes
    $: if (caseId) {
        loading = true;
        loadData();
    }

    async function loadData() {
        try {
            const response = await api.get(`/cases/${caseId}`);
            data = response.data.sinteseAnalitica || {};
            console.log("SinteseAnalitica Data Loaded:", data);
        } catch (err) {
            console.warn(
                "Backend unavailable or error, using Mock Data for SinteseAnalitica",
            );
            data = {
                Unidade_Analitica:
                    "Caso complexo envolvendo violência doméstica e risco de feminicídio.",
                Avaliacao_Riscos:
                    "Alto risco devido ao histórico de ameaças e acesso a armas.",
                Plano_Prevencao:
                    "Encaminhamento para abrigo sigiloso e solicitação de medidas protetivas de urgência.",
                Data_Vencimento: "2025-12-31",
                Cor_Risco: "Vermelho",
            };
        } finally {
            loading = false;
            lastSavedData = JSON.stringify(data);
        }
    }

    async function manualSave() {
        if (saving) return;
        saving = true;
        saveStatus = "Salvando...";

        try {
            await api.put(`/cases/${caseId}/sintese-analitica`, data);
            saveStatus = "Salvo com sucesso! ✅";
            lastSavedData = JSON.stringify(data);
            setTimeout(() => (saveStatus = ""), 3000);
        } catch (err) {
            console.error("Error saving data:", err);
            saveStatus = "Erro ao salvar ❌";
        } finally {
            saving = false;
        }
    }

    function autosave() {
        if (loading) return;

        const currentData = JSON.stringify(data);
        if (currentData === lastSavedData) return;

        clearTimeout(saveTimeout);
        saveTimeout = setTimeout(async () => {
            if (saving) return;
            saving = true;
            saveStatus = "Salvando...";
            try {
                await api.put(`/cases/${caseId}/sintese-analitica`, data);
                console.log("Autosaving SinteseAnalitica...", data);
                saveStatus = "Salvo! ✅";
                lastSavedData = currentData;
                setTimeout(() => (saveStatus = ""), 2000);
            } catch (err) {
                console.error("Error autosaving", err);
                saveStatus = "Erro ao salvar ❌";
            } finally {
                saving = false;
            }
        }, 1000);
    }

    $: if (data) autosave();
</script>

<div class="bg-white rounded shadow p-6 relative">
    <!-- Autosave Indicator -->
    <div
        class="absolute top-4 right-4 text-sm font-medium transition-opacity duration-300"
        class:opacity-0={!saving}
        class:opacity-100={saving}
    >
        <span class="text-save-primary flex items-center">
            <span class="material-icons text-sm mr-1 animate-spin">sync</span>
            Salvando...
        </span>
    </div>
    <div
        class="absolute top-4 right-4 text-sm font-medium transition-opacity duration-300"
        class:opacity-0={saving || loading}
        class:opacity-100={!saving && !loading}
    >
        <span
            class="flex items-center {saveStatus.includes('Erro')
                ? 'text-red-600'
                : 'text-green-600'}"
        >
            {#if saveStatus.includes("Erro")}
                <span class="material-icons text-sm mr-1">error</span>
            {:else if saveStatus.includes("Salvo")}
                <span class="material-icons text-sm mr-1">check</span>
            {/if}
            {saveStatus || "Salvo"}
        </span>
    </div>

    {#if loading}
        <p>Carregando...</p>
    {:else}
        <div class="space-y-6">
            <!-- Indicador de Risco -->
            <div class="border-b pb-4">
                <h3 class="text-lg font-semibold text-gray-700 mb-4">
                    Classificação de Risco
                </h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <label class="block">
                        <span class="text-gray-700">Nível de Risco (Cor)</span>
                        <select
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                            bind:value={data.Cor_Risco}
                        >
                            <option value="">Selecione...</option>
                            <option value="Verde">Verde (Baixo)</option>
                            <option value="Amarelo">Amarelo (Médio)</option>
                            <option value="Vermelho">Vermelho (Alto)</option>
                            <option value="Roxo">Roxo (Extremo)</option>
                        </select>
                    </label>

                    <label class="block">
                        <span class="text-gray-700"
                            >Data de Vencimento / Revisão</span
                        >
                        <input
                            type="date"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                            bind:value={data.Data_Vencimento}
                        />
                    </label>
                </div>
            </div>

            <!-- Análise Técnica -->
            <div>
                <h3 class="text-lg font-semibold text-gray-700 mb-4">
                    Análise Técnica
                </h3>

                <label class="block mb-4">
                    <span class="text-gray-700 font-medium"
                        >Unidade Analítica (Síntese do Caso)</span
                    >
                    <textarea
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        rows="6"
                        bind:value={data.Unidade_Analitica}
                    ></textarea>
                </label>

                <label class="block mb-4">
                    <span class="text-gray-700 font-medium"
                        >Avaliação de Riscos</span
                    >
                    <textarea
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        rows="6"
                        bind:value={data.Avaliacao_Riscos}
                    ></textarea>
                </label>

                <label class="block">
                    <span class="text-gray-700 font-medium"
                        >Plano de Prevenção e Enfrentamento</span
                    >
                    <textarea
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        rows="6"
                        bind:value={data.Plano_Prevencao}
                    ></textarea>
                </label>
            </div>
        </div>
        <!-- Manual Save Button -->
        <div class="md:col-span-2 flex justify-end mt-4">
            <button
                class="bg-save-primary text-white px-6 py-2 rounded shadow hover:bg-save-secondary transition-colors disabled:opacity-50"
                on:click={manualSave}
                disabled={saving || loading}
            >
                {saving ? "Salvando..." : "Salvar Dados"}
            </button>
        </div>
    {/if}
</div>

// SAVe_Web/client/src/pages/cases/SinteseAnalitica.tsx
import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import MainLayout from '../../components/layout/MainLayout';
import FormNavigation from '../../components/forms/FormNavigation';
import { formStepsComplete } from '../../config/formSteps';
import api from '../../services/api';

export default function SinteseAnalitica() {
  const navigate = useNavigate();
  const { id } = useParams();
  const [loading, setLoading] = useState(true);

  const [formData, setFormData] = useState({
    UnidadeAnalitica: '',
    AvaliacaoDeRiscos: '',
    PlanoDePrevencao: '',
    DataVencimento: '',
    Cor: ''
  });

  useEffect(() => {
    if (id) {
      fetchCaseData();
    }
  }, [id]);

  const fetchCaseData = async () => {
    try {
      const response = await api.get(`/cases/${id}`);
      if (response.data.sintese) {
        const data = response.data.sintese;
        setFormData({
          UnidadeAnalitica: data.UnidadeAnalitica || '',
          AvaliacaoDeRiscos: data.AvaliacaoDeRiscos || '',
          PlanoDePrevencao: data.PlanoDePrevencao || '',
          DataVencimento: data.DataVencimento ? data.DataVencimento.split('T')[0] : '',
          Cor: data.Cor || ''
        });
      }
    } catch (error) {
      console.error('Error fetching case data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (field: string, value: any) => {
    try {
      await api.put(`/cases/${id}/sintese`, { [field]: value });
    } catch (error) {
      console.error('Error saving data:', error);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleBlur = (field: string, value: any) => {
    handleSave(field, value);
  };

  const renderTextarea = (label: string, field: string, rows: number = 6) => (
    <div className="mb-6">
      <label className="block text-sm font-semibold mb-2 text-gray-700">{label}</label>
      <textarea
        rows={rows}
        className="w-full px-3 py-2 border border-gray-300 rounded focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
        value={formData[field as keyof typeof formData] as string}
        onChange={(e) => handleChange(field, e.target.value)}
        onBlur={(e) => handleBlur(field, e.target.value)}
      />
    </div>
  );

  const renderInput = (label: string, field: string, type: string = 'text') => (
    <div className="mb-4">
      <label className="block text-sm font-semibold mb-1 text-gray-700">{label}</label>
      <input
        type={type}
        className="w-full px-3 py-2 border border-gray-300 rounded focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
        value={formData[field as keyof typeof formData] as string}
        onChange={(e) => handleChange(field, e.target.value)}
        onBlur={(e) => handleBlur(field, e.target.value)}
      />
    </div>
  );

  const renderColorPicker = (label: string, field: string) => {
    const colors = [
      { value: 'Verde', label: 'Verde (Baixo Risco)', color: 'bg-green-500' },
      { value: 'Amarelo', label: 'Amarelo (Médio Risco)', color: 'bg-yellow-500' },
      { value: 'Laranja', label: 'Laranja (Alto Risco)', color: 'bg-orange-500' },
      { value: 'Vermelho', label: 'Vermelho (Risco Crítico)', color: 'bg-red-500' }
    ];

    return (
      <div className="mb-6">
        <label className="block text-sm font-semibold mb-3 text-gray-700">{label}</label>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {colors.map(color => (
            <button
              key={color.value}
              type="button"
              onClick={() => {
                handleChange(field, color.value);
                handleSave(field, color.value);
              }}
              className={`p-3 rounded-lg border-2 transition-all ${formData[field as keyof typeof formData] === color.value
                  ? 'border-indigo-600 shadow-lg scale-105'
                  : 'border-gray-300 hover:border-gray-400'
                }`}
            >
              <div className={`w-full h-8 ${color.color} rounded mb-2`}></div>
              <p className="text-xs text-center font-medium">{color.label}</p>
            </button>
          ))}
        </div>
      </div>
    );
  };

  return (
    <MainLayout>
      <div className="flex-1 flex flex-col h-screen overflow-hidden">
        <FormNavigation steps={formStepsComplete} caseId={id} />

        <div className="flex-1 overflow-y-auto bg-gray-50 p-8">
          <div className="max-w-7xl mx-auto space-y-6">

            <div className="bg-white rounded-lg shadow p-6 border-2 border-gray-200">
              <h3 className="text-lg font-semibold mb-6 text-gray-800">Síntese Analítica do Caso</h3>

              {renderTextarea('Unidade Analítica:', 'UnidadeAnalitica', 8)}

              {renderTextarea('Avaliação de Riscos:', 'AvaliacaoDeRiscos', 8)}

              {renderTextarea('Plano de Prevenção:', 'PlanoDePrevencao', 8)}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {renderInput('Data de Vencimento:', 'DataVencimento', 'date')}
                <div>
                  {renderColorPicker('Indicador de Risco:', 'Cor')}
                </div>
              </div>
            </div>

            {/* Botões de Navegação */}
            <div className="flex justify-between pt-6">
              <button
                onClick={() => navigate(`/cases/${id}/vitimizacao`)}
                className="px-6 py-2 rounded border border-gray-300 text-gray-700 hover:bg-gray-50"
              >
                Voltar
              </button>
              <button
                onClick={() => navigate(`/cases/${id}/acompanhamento`)}
                className="px-6 py-2 rounded text-white bg-[#6264A7] hover:bg-[#5558a0]"
              >
                Próximo
              </button>
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
