// SAVe_Web/client/src/pages/cases/Encerramento.tsx
import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import MainLayout from '../../components/layout/MainLayout';
import FormNavigation from '../../components/forms/FormNavigation';
import api from '../../services/api';
import { AlertCircle, CheckCircle, Lock } from 'lucide-react';

export default function Encerramento() {
  const navigate = useNavigate();
  const { id } = useParams();

  const [isCaseEncerrado, setIsCaseEncerrado] = useState(false);

  const [formData, setFormData] = useState({
    Data: '',
    Forma_Encerramento_Caso: '',
    Especifique_Outros: '',
    Observacao: ''
  });

  useEffect(() => {
    if (id) {
      fetchCaseData();
    }
  }, [id]);

  const fetchCaseData = async () => {
    try {
      const response = await api.get(`/cases/${id}`);

      // Check if case is already closed
      if (response.data.geral?.Encerrado === 'Sim') {
        setIsCaseEncerrado(true);
      }

      if (response.data.encerramento) {
        const data = response.data.encerramento;
        setFormData({
          Data: data.Data ? data.Data.split('T')[0] : '',
          Forma_Encerramento_Caso: data.Forma_Encerramento_Caso || '',
          Especifique_Outros: data.Especifique_Outros || '',
          Observacao: data.Observacao || ''
        });
      }
    } catch (error) {
      console.error('Error fetching case data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (field: string, value: any) => {
    if (isCaseEncerrado) return; // Prevent editing if case is closed

    try {
      await api.put(`/cases/${id}/encerramento`, { [field]: value });
    } catch (error) {
      console.error('Error saving data:', error);
    }
  };

  const handleChange = (field: string, value: any) => {
    if (isCaseEncerrado) return;
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleBlur = (field: string, value: any) => {
    if (isCaseEncerrado) return;
    handleSave(field, value);
  };

  const handleEncerrarCaso = async () => {
    if (!formData.Data || !formData.Forma_Encerramento_Caso) {
      alert('Por favor, preencha a data e a forma de encerramento antes de encerrar o caso.');
      return;
    }

    if (window.confirm('Tem certeza que deseja encerrar este caso? Esta ação não poderá ser desfeita e o caso ficará bloqueado para edição.')) {
      try {
        // Save encerramento data
        await api.put(`/cases/${id}/encerramento`, formData);

        // Update case status to Encerrado
        await api.put(`/cases/${id}/geral`, { Encerrado: 'Sim' });

        setIsCaseEncerrado(true);
        alert('Caso encerrado com sucesso!');
      } catch (error) {
        console.error('Error closing case:', error);
        alert('Erro ao encerrar o caso. Por favor, tente novamente.');
      }
    }
  };

  const formasEncerramento = [
    'Arquivamento',
    'Transferência',
    'Conclusão do Atendimento',
    'Desistência da Vítima',
    'Óbito',
    'Outros'
  ];

  const renderInput = (label: string, field: string, type: string = 'text', placeholder: string = '') => (
    <div className="mb-4">
      <label className="block text-sm font-semibold mb-1 text-gray-700">{label}</label>
      <input
        type={type}
        className={`w-full px-3 py-2 border border-gray-300 rounded ${isCaseEncerrado ? 'bg-gray-100 cursor-not-allowed' : ''}`}
        placeholder={placeholder}
        value={formData[field as keyof typeof formData] as string}
        onChange={(e) => handleChange(field, e.target.value)}
        onBlur={(e) => handleBlur(field, e.target.value)}
        disabled={isCaseEncerrado}
      />
    </div>
  );

  const renderTextarea = (label: string, field: string, rows: number = 4) => (
    <div className="mb-4">
      <label className="block text-sm font-semibold mb-1 text-gray-700">{label}</label>
      <textarea
        rows={rows}
        className={`w-full px-3 py-2 border border-gray-300 rounded ${isCaseEncerrado ? 'bg-gray-100 cursor-not-allowed' : ''}`}
        value={formData[field as keyof typeof formData] as string}
        onChange={(e) => handleChange(field, e.target.value)}
        onBlur={(e) => handleBlur(field, e.target.value)}
        disabled={isCaseEncerrado}
      />
    </div>
  );

  const renderSelect = (label: string, field: string, options: string[]) => (
    <div className="mb-4">
      <label className="block text-sm font-semibold mb-1 text-gray-700">{label}</label>
      <select
        className={`w-full px-3 py-2 border border-gray-300 rounded ${isCaseEncerrado ? 'bg-gray-100 cursor-not-allowed' : ''}`}
        value={formData[field as keyof typeof formData] as string}
        onChange={(e) => {
          handleChange(field, e.target.value);
          handleSave(field, e.target.value);
        }}
        disabled={isCaseEncerrado}
      >
        <option value="">Selecione...</option>
        {options.map(option => (
          <option key={option} value={option}>{option}</option>
        ))}
      </select>
    </div>
  );

  return (
    <MainLayout>
      <div className="flex-1 flex flex-col h-screen overflow-hidden">
        <FormNavigation caseId={id} />

        <div className="flex-1 overflow-y-auto bg-gray-50 p-8">
          <div className="max-w-7xl mx-auto space-y-6">

            {/* Status Banner */}
            {isCaseEncerrado && (
              <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded">
                <div className="flex items-center">
                  <Lock className="text-yellow-600 mr-3" size={24} />
                  <div>
                    <p className="text-sm font-semibold text-yellow-800">Caso Encerrado</p>
                    <p className="text-sm text-yellow-700">Este caso foi encerrado e não pode mais ser editado.</p>
                  </div>
                </div>
              </div>
            )}

            {/* Formulário de Encerramento */}
            <div className="bg-white rounded-lg shadow p-6 border-2 border-gray-200">
              <div className="flex items-center mb-6">
                {isCaseEncerrado ? (
                  <CheckCircle className="text-green-600 mr-3" size={28} />
                ) : (
                  <AlertCircle className="text-orange-600 mr-3" size={28} />
                )}
                <h3 className="text-lg font-semibold text-gray-800">Encerramento do Caso</h3>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {renderInput('Data de Encerramento:', 'Data', 'date')}
                {renderSelect('Forma de Encerramento:', 'Forma_Encerramento_Caso', formasEncerramento)}
              </div>

              {formData.Forma_Encerramento_Caso === 'Outros' && (
                <div className="mt-4">
                  {renderInput('Especifique Outros:', 'Especifique_Outros', 'text', 'Descreva a forma de encerramento')}
                </div>
              )}

              <div className="mt-4">
                {renderTextarea('Observações:', 'Observacao', 6)}
              </div>

              {!isCaseEncerrado && (
                <div className="mt-6 pt-6 border-t border-gray-200">
                  <div className="bg-orange-50 border border-orange-200 rounded-lg p-4 mb-4">
                    <div className="flex items-start">
                      <AlertCircle className="text-orange-600 mr-3 mt-0.5" size={20} />
                      <div>
                        <p className="text-sm font-semibold text-orange-800 mb-1">Atenção!</p>
                        <p className="text-sm text-orange-700">
                          Ao encerrar o caso, todas as informações serão bloqueadas para edição.
                          Certifique-se de que todos os dados estão corretos antes de prosseguir.
                        </p>
                      </div>
                    </div>
                  </div>

                  <button
                    onClick={handleEncerrarCaso}
                    className="w-full flex items-center justify-center px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 font-semibold transition-colors"
                  >
                    <Lock size={20} className="mr-2" />
                    Encerrar Caso
                  </button>
                </div>
              )}
            </div>

            {/* Informações Adicionais */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-blue-800 mb-2">Informações sobre Encerramento</h4>
              <ul className="text-sm text-blue-700 space-y-1 list-disc list-inside">
                <li>O encerramento do caso é uma ação irreversível</li>
                <li>Após o encerramento, nenhum campo poderá ser editado</li>
                <li>O caso permanecerá visível para consulta</li>
                <li>Certifique-se de que todos os acompanhamentos foram registrados</li>
              </ul>
            </div>

            {/* Botões de Navegação */}
            <div className="flex justify-between pt-6">
              <button
                onClick={() => navigate(`/cases/${id}/acompanhamento`)}
                className="px-6 py-2 rounded border border-gray-300 text-gray-700 hover:bg-gray-50"
              >
                Voltar
              </button>
              <button
                onClick={() => navigate('/cases')}
                className="px-6 py-2 rounded text-white bg-[#6264A7] hover:bg-[#5558a0]"
              >
                Voltar para Lista de Casos
              </button>
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}

// SAVe_New/frontend/src/components/sections/Encerramento.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import api from "../../lib/api";

    export let caseId: string;

    let data: any = {};
    let loading = true;
    let saving = false;
    let saveTimeout: any;
    let lastSavedData: string = "";

    onMount(async () => {
        try {
            const response = await api.get(`/cases/${caseId}/encerramento`);
            data = response.data || {};
        } catch (err) {
            console.warn(
                "Backend unavailable, using Mock Data for Encerramento",
            );
            data = {
                Data_Encerramento: "",
                Forma_Encerramento: "",
                Especifique_Outros: "",
                Observacao: "",
                Encaminhamento_Pos_Alta: "",
            };
        } finally {
            loading = false;
            lastSavedData = JSON.stringify(data);
        }
    });

    function autosave() {
        if (loading) return;

        const currentData = JSON.stringify(data);
        if (currentData === lastSavedData) return;

        clearTimeout(saveTimeout);
        saving = true;

        saveTimeout = setTimeout(async () => {
            try {
                // await api.put(`/cases/${caseId}/encerramento`, data);
                console.log("Autosaving Encerramento...", data);
                await new Promise((r) => setTimeout(r, 500));
                lastSavedData = currentData;
            } catch (err) {
                console.error("Error autosaving", err);
            } finally {
                saving = false;
            }
        }, 1000);
    }

    $: if (data) autosave();

    async function finalizeCase() {
        if (
            !confirm(
                "Tem certeza que deseja encerrar este caso? Esta ação pode bloquear edições futuras.",
            )
        ) {
            return;
        }
        try {
            // await api.put(`/cases/${caseId}/encerramento/finalize`, data);
            alert("Caso encerrado com sucesso! (Simulação)");
        } catch (err) {
            alert("Erro ao encerrar caso");
        }
    }
</script>

<div class="bg-white rounded shadow p-6 relative">
    <!-- Autosave Indicator -->
    <div
        class="absolute top-4 right-4 text-sm font-medium transition-opacity duration-300"
        class:opacity-0={!saving}
        class:opacity-100={saving}
    >
        <span class="text-save-primary flex items-center">
            <span class="material-icons text-sm mr-1 animate-spin">sync</span>
            Salvando...
        </span>
    </div>
    <div
        class="absolute top-4 right-4 text-sm font-medium transition-opacity duration-300"
        class:opacity-0={saving || loading}
        class:opacity-100={!saving && !loading}
    >
        <span class="text-green-600 flex items-center">
            <span class="material-icons text-sm mr-1">check</span>
            Salvo
        </span>
    </div>

    {#if loading}
        <p>Carregando...</p>
    {:else}
        <div class="space-y-6">
            <div class="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">
                <div class="flex">
                    <div class="flex-shrink-0">
                        <span class="material-icons text-yellow-400"
                            >warning</span
                        >
                    </div>
                    <div class="ml-3">
                        <p class="text-sm text-yellow-700">
                            O encerramento do caso indica que não haverá mais
                            acompanhamentos ativos. Certifique-se de que todas
                            as etapas foram concluídas.
                        </p>
                    </div>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <label class="block">
                    <span class="text-gray-700">Data de Encerramento</span>
                    <input
                        type="date"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        bind:value={data.Data_Encerramento}
                    />
                </label>

                <label class="block">
                    <span class="text-gray-700">Motivo do Encerramento</span>
                    <select
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        bind:value={data.Forma_Encerramento}
                    >
                        <option value="">Selecione...</option>
                        <option value="Conclusão do Plano"
                            >Conclusão do Plano de Acompanhamento</option
                        >
                        <option value="Evasão">Evasão / Perda de Contato</option
                        >
                        <option value="Transferência"
                            >Transferência para outro serviço</option
                        >
                        <option value="Óbito">Óbito</option>
                        <option value="Outros">Outros</option>
                    </select>
                </label>
            </div>

            {#if data.Forma_Encerramento === "Outros"}
                <label class="block">
                    <span class="text-gray-700">Especifique</span>
                    <input
                        type="text"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                        bind:value={data.Especifique_Outros}
                    />
                </label>
            {/if}

            <label class="block">
                <span class="text-gray-700">Encaminhamento Pós-Alta</span>
                <input
                    type="text"
                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                    bind:value={data.Encaminhamento_Pos_Alta}
                />
            </label>

            <label class="block">
                <span class="text-gray-700">Observações Finais</span>
                <textarea
                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-save-primary focus:ring focus:ring-save-primary/30"
                    rows="4"
                    bind:value={data.Observacao}
                ></textarea>
            </label>
        </div>

        <div class="mt-6 flex justify-end">
            <button
                class="bg-red-600 text-white px-6 py-2 rounded hover:bg-red-700 transition shadow flex items-center"
                on:click={finalizeCase}
            >
                <span class="material-icons mr-2">lock</span> Encerrar Caso
            </button>
        </div>
    {/if}
</div>
