// SAVe_New/frontend/src/routes/Login.svelte
<script lang="ts">
  import api from "../lib/api";
  import LoadingScreen from "../components/LoadingScreen.svelte";

  let email = "";
  let password = "";
  let error = "";
  let loading = false;
  let showLoadingScreen = false;

  function handleSubmit(e: Event) {
    e.preventDefault();
    handleLogin();
  }

  async function handleLogin() {
    loading = true;
    error = "";
    try {
      const response = await api.post("/login", { email, password });
      localStorage.setItem("token", response.data.token);
      localStorage.setItem("user", JSON.stringify(response.data.user));

      // Show loading screen animation
      showLoadingScreen = true;
    } catch (err: any) {
      console.error("Login error:", err);
      if (err.response) {
        error = err.response.data.error || "Erro ao fazer login";
      } else {
        error = "Erro de conexão com o servidor";
      }
    } finally {
      loading = false;
    }
  }

  function onLoadingComplete() {
    window.location.href = "/menu";
  }
</script>

{#if showLoadingScreen}
  <LoadingScreen onComplete={onLoadingComplete} />
{:else}
  <div
    class="min-h-screen flex items-center justify-center bg-save-surface font-sans"
  >
    <div
      class="bg-white p-8 rounded-xl shadow-xl w-full max-w-md border border-gray-100"
    >
      <div class="text-center mb-8">
        <div
          class="w-20 h-20 mx-auto mb-4 rounded-full flex items-center justify-center bg-save-primary shadow-lg"
        >
          <svg
            class="w-10 h-10 text-white"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
            />
          </svg>
        </div>
        <h1 class="text-3xl font-bold text-gray-800 tracking-tight">SAVe</h1>
        <p class="text-sm text-gray-500 mt-2">
          Sistema de Avaliação de Vitimização Eletrônico
        </p>
      </div>

      <form on:submit={handleSubmit} class="space-y-6">
        {#if error}
          <div
            class="p-4 rounded-md bg-red-50 text-red-700 text-sm border border-red-100"
          >
            {error}
          </div>
        {/if}

        <div>
          <label
            for="email"
            class="block text-sm font-medium mb-2 text-gray-700"
          >
            Email Institucional
          </label>
          <input
            id="email"
            type="email"
            bind:value={email}
            required
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-save-primary/50 focus:border-save-primary transition-all"
            placeholder="seu.email@mpmg.mp.br"
          />
        </div>

        <div>
          <label
            for="password"
            class="block text-sm font-medium mb-2 text-gray-700"
          >
            Senha
          </label>
          <input
            id="password"
            type="password"
            bind:value={password}
            required
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-save-primary/50 focus:border-save-primary transition-all"
            placeholder="••••••••"
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          class="w-full py-3 rounded-lg font-bold text-white transition-all transform active:scale-95 disabled:opacity-70 disabled:cursor-not-allowed shadow-md hover:shadow-lg bg-save-primary hover:bg-save-secondary"
        >
          {loading ? "Autenticando..." : "Acessar Sistema"}
        </button>
      </form>

      <div class="mt-8 text-center text-xs text-gray-400">
        <p>© 2024 Ministério Público de Minas Gerais</p>
        <p class="mt-1">Versão 2.0.0 (Svelte Edition)</p>
      </div>
    </div>
  </div>
{/if}

// SAVe_Web/client/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Login() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError('');
        setLoading(true);

        try {
            await login(email, password);
            navigate('/dashboard');
        } catch (err: any) {
            setError(err.response?.data?.error || 'Erro ao fazer login');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: '#F3F2F1' }}>
            <div className="bg-white p-8 rounded-lg shadow-lg w-full max-w-md">
                <div className="text-center mb-8">
                    <div className="w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center" style={{ backgroundColor: '#6264A7' }}>
                        <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                        </svg>
                    </div>
                    <h1 className="text-2xl font-bold" style={{ color: '#323130' }}>SAVe</h1>
                    <p className="text-sm" style={{ color: '#605E5C' }}>Sistema de Avaliação de Vitimização Eletrônico</p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                    {error && (
                        <div className="p-3 rounded text-sm" style={{ backgroundColor: '#FDE7E9', color: '#D13438' }}>
                            {error}
                        </div>
                    )}

                    <div>
                        <label htmlFor="email" className="block text-sm font-medium mb-2" style={{ color: '#323130' }}>
                            Email
                        </label>
                        <input
                            id="email"
                            type="email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                            className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2"
                            style={{ borderColor: '#D2D0CE', focusRingColor: '#6264A7' }}
                            placeholder="seu.email@mpmg.mp.br"
                        />
                    </div>

                    <div>
                        <label htmlFor="password" className="block text-sm font-medium mb-2" style={{ color: '#323130' }}>
                            Senha
                        </label>
                        <input
                            id="password"
                            type="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            required
                            className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2"
                            style={{ borderColor: '#D2D0CE' }}
                            placeholder="••••••••"
                        />
                    </div>

                    <button
                        type="submit"
                        disabled={loading}
                        className="w-full py-3 rounded font-medium text-white transition-colors disabled:opacity-50"
                        style={{ backgroundColor: '#6264A7' }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#4A4C8A'}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#6264A7'}
                    >
                        {loading ? 'Entrando...' : 'Entrar'}
                    </button>
                </form>

                <div className="mt-6 text-center text-xs" style={{ color: '#605E5C' }}>
                    <p>© 2024 Ministério Público de Minas Gerais</p>
                </div>
            </div>
        </div>
    );
}
